export default interface globalData {
    account: any,
    recipient: any,
    amount: any,
    tokenBalance: any,
    coinBalance: any,
    coinSymbol: any,
    AmountInForSwap: any,
    AmountOutForSwap: any,
    chainName: any,
    coinPrice: any,
    name: any,
    decimal: any,
    symbol: any,
    supply: any,
    connectedBool: boolean,
    SourceChainIdInHexa: any,
    TargetChainIdInHexa: any,
    errorMessage: string,
    tips: string,
    coinUSDCPair: any,
};
